/**
 * Server-side image generation for the AI website generator. Turns an
 * ImageSpec `prompt` into a real CDN asset: calls the OpenAI Images API
 * (base64 JPEG), uploads the bytes via q-profile/image/create, and returns the
 * stored `file_name` (CDN key). Best-effort throughout — a failed image never
 * throws, it just leaves `fileName` undefined so the page still renders.
 *
 * Model: `gpt-image-2.5-flare` (fast tier of the current generation). The
 * original `gpt-image-1` is deprecated by OpenAI with shutdown on 2026-12-01
 * (developers.openai.com/api/docs/deprecations), so it must not be the default
 * any more. Override with OPENAI_IMAGE_MODEL. Verified 2026-09-17: the same
 * request body (size/quality/output_format/output_compression) works on the
 * new model; a 1024² low-quality JPEG is ~100 KB and ~200 output tokens.
 *
 * Node runtime only (uses global Buffer/File). Dependency-free: plain `fetch`
 * + the existing `uploadImage` helper.
 */

const OPENAI_IMAGES_URL = "https://api.openai.com/v1/images/generations";
const IMAGE_MODEL = process.env.OPENAI_IMAGE_MODEL || "gpt-image-2.5-flare";
// Smallest square. Keep files light + generation fast: low quality + JPEG
// compression cuts file size ~10x and speeds each render. Callers may pass a
// landscape size (e.g. "1536x1024") for wide hero covers.
const DEFAULT_SIZE = "1024x1024";
const IMAGE_QUALITY = "low"; // low | medium | high | auto
const OUTPUT_FORMAT = "jpeg"; // jpeg → far smaller than PNG
const OUTPUT_COMPRESSION = 65; // 0-100 (jpeg/webp only)
const API_BASE = process.env.NEXT_PUBLIC_API_BASE ?? "https://api.qshot.com";

/**
 * Upload generated bytes to the CDN (q-profile/image/create) using the END
 * USER's bearer token — the shared `api` client reads the token from a browser
 * store that does NOT exist server-side, so we must fetch directly with the
 * token threaded from the request. Returns the stored file_name or undefined.
 */
async function uploadGenerated(file: File, auth?: string): Promise<string | undefined> {
  if (!auth) return undefined;
  // Concurrent multipart uploads to the CDN can drop the connection ("fetch
  // failed"); retry a couple of times with a short backoff.
  for (let attempt = 0; attempt < 3; attempt++) {
    try {
      const form = new FormData();
      form.append("images", file);
      const res = await fetch(`${API_BASE}/q-profile/image/create`, {
        method: "POST",
        headers: { Authorization: auth, Accept: "application/json" },
        body: form,
      });
      if (res.ok) {
        const j = (await res.json()) as { data?: { file_name?: string }[] };
        const name = j?.data?.[0]?.file_name;
        if (name) return name;
      }
    } catch {
      /* transient — retry */
    }
    await new Promise((r) => setTimeout(r, 500 * (attempt + 1)));
  }
  return undefined;
}

/** Run async `fn` over `items` with at most `limit` in flight (the CDN can't
 * take many concurrent multipart uploads). */
async function pool<T>(
  items: T[],
  limit: number,
  fn: (item: T, index: number) => Promise<void>,
): Promise<void> {
  let i = 0;
  const workers = Array.from({ length: Math.min(Math.max(1, limit), items.length) }, async () => {
    while (i < items.length) {
      const idx = i++;
      await fn(items[idx], idx);
    }
  });
  await Promise.all(workers);
}

/** Vivid, clean modern photographic look — appended to every model prompt. */
const STYLE_SUFFIX =
  "professional photograph, modern and clean, soft natural lighting, " +
  "high detail, tasteful composition, no text, no letters, no logos, " +
  "no watermarks.";

/** Base64 → File (global File/Buffer, Node 20+). JPEG to keep uploads light. */
function base64ToFile(
  b64: string,
  name = "ai-image.jpg",
  type = "image/jpeg",
): File {
  const bytes = Buffer.from(b64, "base64");
  return new File([bytes], name, { type });
}

/**
 * Generate one image from `prompt` and upload it to the CDN. Returns the stored
 * `file_name`, or `undefined` on any failure (never throws).
 */
export async function generateImage(
  prompt: string,
  auth?: string,
  opts?: { size?: string },
): Promise<string | undefined> {
  const key = process.env.OPENAI_API_KEY;
  if (!key || !auth || !prompt.trim()) return undefined;

  try {
    const res = await fetch(OPENAI_IMAGES_URL, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${key}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: IMAGE_MODEL,
        prompt: `${prompt.trim()} ${STYLE_SUFFIX}`,
        size: opts?.size ?? DEFAULT_SIZE,
        quality: IMAGE_QUALITY,
        output_format: OUTPUT_FORMAT,
        output_compression: OUTPUT_COMPRESSION,
        n: 1,
      }),
    });
    if (!res.ok) return undefined;

    const json = (await res.json()) as {
      data?: { b64_json?: string }[];
    };
    const b64 = json.data?.[0]?.b64_json;
    if (!b64) return undefined;

    return await uploadGenerated(base64ToFile(b64), auth);
  } catch {
    return undefined;
  }
}

/**
 * Generate up to `cap` specs in parallel, setting `spec.fileName` on each
 * (mutates in place). Best-effort: failures leave `fileName` undefined. Specs
 * beyond the cap are left untouched.
 */
export async function resolveImageSpecs(
  specs: Array<{ prompt: string; fileName?: string; size?: string }>,
  cap: number,
  auth?: string,
): Promise<void> {
  if (!auth) return;
  const slice = specs.slice(0, Math.max(0, cap));
  // Limit concurrency: the Images API tolerates parallelism, but the CDN upload
  // drops connections under load. 3-in-flight + retry balances speed + reliability.
  await pool(slice, 3, async (spec) => {
    spec.fileName = await generateImage(spec.prompt, auth, { size: spec.size });
  });
}
